### ISSUE TITLE
How to run after build succeeded?

### ISSUE THREAD

**Issue by nikivdev** [rounak/MLXTinyGPT#1]
<img width="523" alt="image" src="https://github.com/rounak/MLXTinyGPT/assets/6391776/a30ff689-66c4-4150-a1fd-e73b2e42e1ae">

I got this but not sure what to do now. I don't see any binaries produced.

I am curious how you worked on this repo, like what is the run/debug cycle like?

Thanks. 🖤

**Comment by nikivdev** [comment]
It seems its training the whole neural net now? Can I stop it earlier or how does it know when to end training?

<img width="959" alt="image" src="https://github.com/rounak/MLXTinyGPT/assets/6391776/b0ba7cdd-92e1-4ce4-b582-2b98cca92097">

**Comment by rounak** [comment]
@nikitavoloboev Hi! thanks for trying the project. Yes, it trains the neural network for 5000 epochs, and then generates text based on it. The training takes about 15-20 mins.

**Comment by rounak** [comment]
@nikitavoloboev I've updated the code to now use pre-trained weights. Try it!
